CourseRegistrationNew/Models/Students.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using CourseRegistrationNew.Models;

namespace CourseRegistrationNew.Models
{
    public class Students
    {
        public Students()
        {

        }

        [Key]
        public int StudentID { get; set; }
        [Required]
        [Display(Name = "First Name")]
        [StringLength(50)]
        public string FirstName { get; set; }
        [Required]
        [Display(Name = "Last Name")]
        [StringLength(50)]
        public string LastName { get; set; }
        [RegularExpression(@"^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$",
            ErrorMessage = "Invalid Email Format")]
        public string EmailAddress { get; set; }
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
            ErrorMessage = "Not a valid phone number")]
        public string PhoneNumber { get; set; }

        // acording to data studenr can take few corses
        public List<CoursesStudents> CoursesList { set; get; }
    }

}

CourseRegistrationNew/Controllers/CoursesStudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CourseRegistrationNew.Models;

namespace CourseRegistrationNew.Controllers
{
    public class CoursesStudentsController : Controller
    {
        private readonly DbContextCourse _context;

        public CoursesStudentsController(DbContextCourse context)
        {
            _context = context;
        }
        public IActionResult AddCourse(int studentId, int courseId)
        {

              _context.CoursesStudents
                .Add(new CoursesStudents 
                    { 
                        StudentID = studentId, 
                        CourseID = courseId 
                    });

            _context.SaveChanges();

            return RedirectToAction("Edit", "Students", new { id = studentId } );

        }

        
       
        
    }
}

CourseRegistrationNew/Controllers/StudentsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CourseRegistrationNew.Models;


namespace CourseRegistrationNew.Controllers
{
    public class StudentsController : Controller
    {
        private readonly DbContextCourse _context;

        public StudentsController(DbContextCourse context)
        {
            _context = context;
        }

        // GET: Students
        public async Task<IActionResult> Index()
        {
            return View(await _context.Students.ToListAsync());
        }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var students = await _context.Students
                .FirstOrDefaultAsync(m => m.StudentID == id);

            var courses =  await _context.CoursesStudents
               .Where(sc => sc.StudentID == id)
               .Select(c => c.Course)
               .ToListAsync();

            ViewBag.Courses = courses;



            if (students == null)
            {
                return NotFound();
            }

            return View(students);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StudentID,FirstName,LastName,EmailAddress,PhoneNumber")] Students students)
        {
            if (ModelState.IsValid)
            {
                _context.Add(students);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(students);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var students = await _context.Students.FindAsync(id);

            //take all courses
            var courses =  _context.CoursesStudents
               .Where(sc => sc.StudentID == id)
               .Select(c => c.Course)
               .ToList();

            ViewBag.Courses = courses;

            //all courses minus couses that sudent registered
            ViewBag.AvailableCourses = _context.Courses.AsEnumerable()
                .Except(courses)
                .ToList();

            if (students == null)
            {
                return NotFound();
            }
            return View(students);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StudentID,FirstName,LastName,EmailAddress,PhoneNumber")] Students students)
        {
            if (id != students.StudentID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(students);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentsExists(students.StudentID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(students);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var students = await _context.Students
                .FirstOrDefaultAsync(m => m.StudentID == id);
            if (students == null)
            {
                return NotFound();
            }

            return View(students);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var students = await _context.Students.FindAsync(id);
            _context.Students.Remove(students);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentsExists(int id)
        {
            return _context.Students.Any(e => e.StudentID == id);
        }
    }
}

CourseRegistrationNew/Views/Students/Create.cshtml
@model CourseRegistrationNew.Models.Students

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Students</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input id="inputName" asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
                <p id="NameValidationMessage"></p>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input id="inputLastName" asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
                <p id="LastNameValidationMessage"></p>
            </div>
            <div class="form-group">
                <label asp-for="EmailAddress" class="control-label"></label>
                <input id="inputEmail" asp-for="EmailAddress" class="form-control" />
                <span  asp-validation-for="EmailAddress" class="text-danger"></span>
                <p id="EmailValidationMessage"></p>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input id = "inputPhone" asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                <p id="PhoneValidationMessage"></p>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CourseRegistrationNew/Views/Students/Delete.cshtml
@model CourseRegistrationNew.Models.Students

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Students</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="StudentID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CourseRegistrationNew/Views/Students/Details.cshtml
@model CourseRegistrationNew.Models.Students

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Students</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
</div>

<div>
    <h4>Courses:</h4>
    <dl class="dl-horizontal">

        @foreach (var item in ViewBag.Courses)
        {
                <dt>Name: </dt>
                <dd>@item.CourseName</dd>
        }

    </dl>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model.StudentID">Edit</a> <br>
    <a asp-action="Index">Back to List</a>
</div>

CourseRegistrationNew/Views/Students/Edit.cshtml
@model CourseRegistrationNew.Models.Students

@{ ViewData["Title"] = "Edit"; }

<h1>Edit</h1>

<h4>Students</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StudentID" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input id="inputName" asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
                <p id="NameValidationMessage"></p>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input id="inputLastName" asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
                <p id="LastNameValidationMessage"></p>
            </div>
            <div class="form-group">
                <label asp-for="EmailAddress" class="control-label"></label>
                <input id = "inputEmail" asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
                <p id="EmailValidationMessage"></p>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input id="inputPhone" asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                <p> id="PhoneValidationMessage"></p>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <h4>Courses:</h4>

    <dl class="row-12">


        @foreach (var item in ViewBag.Courses)
        {
                <dt class="col-sm-3">Name: </dt>
                <dd class="col-sm-9">@item.CourseName</dd>
         }

    </dl>
</div>

@if (ViewBag.AvailableCourses != null)
{
<div>
    <h4>Add Course:</h4>

    @using (Html.BeginForm("AddCourse", "CoursesStudents", FormMethod.Get))
    {
                    @Html.Hidden("StudentId", Model.StudentID)
                    @Html.DropDownList("CourseId",
                           new SelectList(ViewBag.AvailableCourses, "CourseID", "CourseName"))

                    <input type="submit" value="Add" class="btn btn-primary" />}
</div>}

<div>
    <a asp-action="Index">Back to List</a>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

CourseRegistrationNew/Views/Students/Index.cshtml
@model IEnumerable<CourseRegistrationNew.Models.Students>

@{
    ViewData["Title"] = "Students";
}
 
<h1>Students: </h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                First Name
            </th>
            <th>
                Last Name
            </th>
            <th>
                Email Address
            </th>
            <th>
               Phone Number
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.StudentID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.StudentID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.StudentID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>